<?php

namespace EML\CmsBundle\Entity;

use Doctrine\ORM\EntityRepository;

/**
 * FeaturedstypeRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class FeaturedstypeRepository extends EntityRepository
{
}
