<?php

namespace EML\CmsBundle\Entity;

use Doctrine\ORM\EntityRepository;

/**
 * MenustypeRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class MenustypeRepository extends EntityRepository
{
}
