<?php

namespace EML\CmsBundle\Entity;

use Doctrine\ORM\EntityRepository;

/**
 * TagElementRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class TagElementRepository extends EntityRepository
{
}
